### ISSUE TITLE
error loading python dll

### ISSUE THREAD

**Issue by 214748** [Jo-Dan/The-Machine#3]
Hi, I installed files ,machine.exe and python2.7. However, it says error loading python dll(error code 14001 )when I run the machine.exe. I am assured that Python is installed correctlly. Can you please tell me how to fix it? by the way, I am a really big fan of POI.

**Comment by Jo-Dan** [comment]
Do you have AVbin installed? I discovered a while ago that the exe crashed immediately without it (whereas the python script crashes when you try to use voice control)

**Comment by Jo-Dan** [comment]
I've updated the Readme to reflect this now. Probably should have done it earlier sorry but didn't bother because no one  really seemed interested in the program.

**Comment by 214748** [comment]
Hey it's me again.Now I can run it correctly but I keeps return "no face detected".Is it because I didn't set csv file correctly?

**Comment by Jo-Dan** [comment]
No face detected? Does it draw a box around your face at all? If not I'll have to look into that. The CSV file just stores the info about the different users in the system. 
Where does it say no face detected?

**Comment by Jo-Dan** [comment]
Where does it say no face detected?

**Comment by Jo-Dan** [comment]
Actually looking at the code and fucking about with the CSV I think that might be the issue. 

Open the CSV in notepad and copy paste it here. (or attach it to your comment, that's probably better to be honest)

**Comment by Jo-Dan** [comment]
This is what the csv should look like when opened in excel or another spreadsheet program (obviously the Names and designations can be whatever you want).
https://drive.google.com/open?id=0B_8BvSoNTOu6MHVTeUxSdDRwUFU

**Comment by Jo-Dan** [comment]
Hey man did you fix the issue? This was a month ago so I'm curious to know whether it works or not.

**Comment by 214748** [comment]
Yeah,it really worked.Sorry, I didn't check my mail.It's a great project.Thank you.
