### ISSUE TITLE
Needs OpenCV with Extras

### ISSUE THREAD

**Issue by pr0fess0r** [Jo-Dan/The-Machine#4]
Hi, thanks for this great app, I just binge watched the series and this was fun to play with! I just built it on Windows 10 with Visual Studio 2017. I already had Python 3.5 installed for TensorFlow so I added 2.7 and got this to work, but I had to build OpenCV with extras following this great tutorial: https://stackoverflow.com/questions/37517983/opencv-install-opencv-contrib-on-windows#_=_

So this isn't a bug but the Reddit thread is closed and there's nowhere else to comment and say thanks :)

**Comment by Jo-Dan** [comment]
That's why I uploaded my own build of open cv (there should be a link in the readme) with the extras already done. I knew how much of a pain it could be to do. 

Anyway I'm really glad you liked the program, I certainly enjoyed making it (it was my first semi major project that I did to help teach myself python) .

**Comment by Jo-Dan** [comment]
If you have any questions about how it works or any features feel free to ask (although I am travelling for 8 months so u won't be able to make changes 😂.

**Comment by pr0fess0r** [comment]
Thanks Jo-Dan, the precompiled build of OpenCV didn't work for me in Windows 10, maybe it needed all the DLLs as well, but it's fine now :) I'm learning Python and Neural Networks now thanks to PoI lol, I just finished the last ep yesterday ;( Thaks again for your work on this, I'll go through it and learn from your code.. where are you traveling? I'm in France lol

**Comment by Jo-Dan** [comment]
Oh really, that's strange.  

Everywhere, including France.
