### ISSUE TITLE
why i type all commands，console shows “Unknown subject detected. Access Denied”

### ISSUE THREAD

**Issue by yanqiangmiffy** [Jo-Dan/The-Machine#6]
G:\ProgramData\Anaconda3\envs\py27\python.exe C:/Users/yanqiang/Desktop/The-Machine/machine.py
Camera Number >>> 0
Would you like to (r)ebuild, or (l)oad the database? >>> r
Display images loaded? (slower) (y/n) >>> y
Training faces .  .  .  .  .  .  .  
Training complete
What are your commands?
>>> info
Unknown subject detected. Access Denied
>>>

**Comment by yanqiangmiffy** [comment]
Subject No.,Name,Type (ADMIN/USER/THREAT/ANALOG/UNKNOWN)
1,YANQIANG,ADMIN
2,YANQIANG,ADMIN
3,YANQIANG,ADMIN
4,YANQIANG,ADMIN
5,YANQIANG,ADMIN
6,YANQIANG,ADMIN

**Comment by Jo-Dan** [comment]
~~I assume you set up the CSV file correctly?~~ Sometimes there are synchronisation issues between the command prompt and the face detection, try sending the command a whole heap of times with your face in the frame maybe? I don't know the cause of the issue sorry, I had the same thing happen occasionally and I'm travelling now so I can't have a look at the files easily.

**Comment by Jo-Dan** [comment]
Hmm, I'd say only put yourself once, I doubt it would cause this issue but it could affect some commands.

**Comment by yanqiangmiffy** [comment]
with open('subjects.csv', "rb") as subjects:
    reader = csv.reader(subjects)
    subject_name = []
    subject_type = []
    for row in reader:
        subject_name.append(row[1])
        if len(row[2]) == 0 or row[2].upper() not in subject_types:
            subject_type.append('UNKNOWN')
        else:
            subject_type.append(row[2])
    subject_name = [x.upper() for x in subject_name]
    subject_type = [x.upper() for x in subject_type]
    log_file.write('   CSV Read. \n')
    subject_type[0] = "UNKNOWN"
    subject_name[0] = "UNKNOWN"

why  subject_type[0] = "UNKNOWN"
    subject_name[0] = "UNKNOWN"？

**Comment by Jo-Dan** [comment]
Why are you sending me this? I can look at the files in github, the problem is that I can't test any changes I make.
Edit: oh I see what you're saying. That simply sets the headings of the csv file.

**Comment by yanqiangmiffy** [comment]
Thank you very much。I understand what you say.I think the program is running normaly,maybe because the pictures I put are the same.thanks,i would try some other pictures

**Comment by Jo-Dan** [comment]
Oh I see. What coloured box is it showing around your head? You do need a variety of photos of your face for the program to work well.

**Comment by yanqiangmiffy** [comment]
it`s a white rectangle frame。now ，I add 45 my photos，but after commands ，**“Unknown subject detected. Access Denied”** has showed。After training all photos,the path "facebase/1/" dont created the file “subject01.normal” like in path **"facebase/0/subject00.normal"** ，

**Comment by Jo-Dan** [comment]
If it's a white rectangle it's not an issue with the code timing. It means it just can't recognise you,  if it could the rectangle would be yellow (because you're an admin) . 

I don't know what you mean by 
>After training all photos,the path "facebase/1/" dont created the file “subject01.normal” like in path "facebase/1/" ，

**Comment by yanqiangmiffy** [comment]
Thanks,I know problems where happened. Above all,（1）The photos is more various，the effect is better  (2) Another reason  is that my camera is not good  and the light in my room is doom,so it cant detect my face.Then I change another camera in stronger light。Finally，thanks for your patient answers and the work is excellent，I would learn more from the project。

**Comment by Jo-Dan** [comment]
So everything is working now? Good to know,  hope you enjoy it.

**Comment by Frankystew1** [comment]
@Jo-Dan @yanqiangmiffy how do i add photos to file
