### ISSUE TITLE
Camera number

### ISSUE THREAD

**Issue by KaKi87** [Jo-Dan/The-Machine#8]
Hello,

`Camera Number >>>`

Where do I find that camera number ?

Thanks.

**Comment by Jo-Dan** [comment]
Oh wow this is an old project. The camera number should be 0, 1, or 2 usually. Just experiment with those until it runs.

**Comment by Jo-Dan** [comment]
Just a warning though that the voice responses no longer work because the voice service it used got shut down.

**Comment by KaKi87** [comment]
Well, all software projects for PoI I found are dead, anyway (usually just before or just after the first release).

You wouldn't re-launch it, right ? 😅
Le 28 janv. 2019, à 00:50, Jo-Dan <notifications@github.com<mailto:notifications@github.com>> a écrit:

Oh wow this is an old project. The camera number should be 0, 1, or 2 usually. Just experiment with those until it runs.

**Comment by Jo-Dan** [comment]
I doubt I'll fix the voice functions to be honest but everything else should work. 
I actually ran it on my laptop a few weeks ago and it was working.

**Comment by KaKi87** [comment]
Okay, what about that ?
```
OpenCV Error: Unsupported format or combination of formats (Empty training data was given. You'll need more than one sample to learn a model.) in cv::face::LBPH::train, file D:\BackUp\F\Users\Jordan\Documents\Python\face recognition setup\OpenCV\Source\opencv_contrib\modules\face\src\lbph_faces.cpp, line 346
Traceback (most recent call last):
  File "machine.py", line 157, in <module>
    database_load(True)
  File "machine.py", line 142, in database_load
    recognizer.train(images, np.array(labels))
cv2.error: D:\BackUp\F\Users\Jordan\Documents\Python\face recognition setup\OpenCV\Source\opencv_contrib\modules\face\src\lbph_faces.cpp:346: error: (-210) Empty training data was given. You'll need more than one sample to learn a model. in function cv::face::LBPH::train

Failed to execute script machine
```

**Comment by Jo-Dan** [comment]
You need to follow the instructions on the readme. You either haven't put face photos in the folder or done CSV file.

**Comment by vpelissi** [comment]
i have the same problems 

OpenCV Error: Unsupported format or combination of formats (Empty training data was given. You'll need more than one sample to learn a model.) in cv::face::LBPH::train, file D:\BackUp\F\Users\Jordan\Documents\Python\face recognition setup\OpenCV\Source\opencv_contrib\modules\face\src\lbph_faces.cpp, line 346
Traceback (most recent call last):
  File "machine.py", line 157, in <module>
    database_load(True)
  File "machine.py", line 142, in database_load
    recognizer.train(images, np.array(labels))
cv2.error: D:\BackUp\F\Users\Jordan\Documents\Python\face recognition setup\OpenCV\Source\opencv_contrib\modules\face\src\lbph_faces.cpp:346: error: (-210) Empty training data was given. You'll need more than one sample to learn a model. in function cv::face::LBPH::train

Failed to execute script machine
:(

**Comment by Jo-Dan** [comment]
You need to follow the readme instructions. You need to create a folder with some face images in the correct location before you start the program.

**Comment by vpelissi** [comment]
now it's working but I have this error No face detected :(

**Comment by Jo-Dan** [comment]
You're going to have to be more specific.

**Comment by vpelissi** [comment]
![machine](https://user-images.githubusercontent.com/9217014/61375408-22493400-a89f-11e9-9533-2b7ef55dbd35.jpg)

no juste that

**Comment by Jo-Dan** [comment]
Yes but at what stage of the program. And where does it say it? This is a super old project so I can't remember everything off the top of my head.
